{
    "name": "Restaurant Inventory",
    "version": "18.0.1.0.0",
    "category": "Operations/Restaurant",
    "summary": "Stock-linked availability and inventory management for restaurant",
    "author": "Your Name",
    "website": "https://github.com/StevenBahaa/restaurant_system",
    "depends": [
        "restaurant_base",
        "restaurant_menu",
        "restaurant_recipe",
        "stock",
    ],
    "data": [
        "security/ir_rules.xml",
        "security/ir.model.access.csv",
        "views/restaurant_recipe_views.xml",
        "views/restaurant_addon_views.xml",
        "views/restaurant_branch_stock_override_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
